### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by QABoahene** [unitaryai/detoxify#10]
`RuntimeError: /Users/qab/.cache/torch/checkpoints/toxic_original-c1212f89.ckpt is a zip archive (did you mean to use torch.jit.load()?)
`
I get this error trying to run this for the first time. Any help?

**Comment by jamt9000** [comment]
Hello! This happens because you are using an old version of pytorch, you will have to use pytorch >= 1.7 (see #3)

**Comment by QABoahene** [comment]
It worked. Thanks!
