### ISSUE TITLE
Issues when training unintended bias model 

### ISSUE THREAD

**Issue by MLRadfys** [unitaryai/detoxify#110]
Hi and thanks for this great repository!

I tried to fine tune the Roberta model on my own for unintended bias in comments classification.
Unfortunately, all of the subgroup AUCs are close to 0.5.

I used the standard configuration given in this repo.

Does anyone tried fine tuning the models on their own? 

I also evaluated the unbiased model given in the repo, leading to a similar result:

![image](https://github.com/unitaryai/detoxify/assets/17001704/70ac2956-28af-498e-ba35-9ff842f8b1db)

Thanks in advance,

/M

**Comment by MLRadfys** [comment]
Hi again!

My fault --> I evaluated on public_test.csv and computed the bias AUCs on private_test.csv :-(
Now it is working :-)

/M

**Comment by jamt9000** [comment]
Glad you got it working!
