### ISSUE TITLE
Problem launching the model

### ISSUE THREAD

**Issue by JohnPFL** [unitaryai/detoxify#3]
Hello,
first of all thanks for your work. This model would amazing to use helping my company in comment-moderation around the social networks.
I followed your guide, but when I launch this to test the model:
`python run_prediction.py --input 'example' --model_name original`
I get this error:
`RuntimeError: Only one file(not dir) is allowed in the zipfile`

**Comment by laurahanu** [comment]
Hello,

Thank you for raising this! It seems like this is caused by using torch 1.6:
https://github.com/pytorch/pytorch/issues/42239

Could you try again using torch 1.7, I just updated the requirements to reflect this as well!

**Comment by JohnPFL** [comment]
Perfect. Now it works!
Thanks again.
