### ISSUE TITLE
Unable to properly load state_dict

### ISSUE THREAD

**Issue by alu13** [unitaryai/detoxify#48]
Code is very basic. Just two lines on Google Colab after pip install detoxify

states that state_dict is Nonetype and thus cannot load the model. Unsure how to fix.

<img width="720" alt="Screen Shot 2022-04-06 at 1 29 41 PM" src="https://user-images.githubusercontent.com/12601917/162033768-3a1a0b63-d4a7-48ac-8ec9-8d73fbe82788.png">

**Comment by mrk-rebel** [comment]
I've been experiencing the same problem the entire day. 

![image](https://user-images.githubusercontent.com/54968195/162107433-cced333c-fdc5-4bf7-a914-c83c93405995.png)

**Comment by laurahanu** [comment]
Thank you for letting us know, we will look into this asap!

**Comment by laurahanu** [comment]
This seems to be a problem related to the latest transformers version 4.18.0. I've submitted an issue for now and we will pin the version to the previous one soon while this gets sorted! For now, please use `transformers <= 4.17.0`

**Comment by laurahanu** [comment]
We just released v0.5.0 that should solve this problem so closing this issue!
