### ISSUE TITLE
GPU not used during Training

### ISSUE THREAD

**Issue by grecosalvatore** [unitaryai/detoxify#66]
Hi there,
Thank you for the useful repository.

I am trying to use the script for model training.  By leaving the "--device" parameter with the default value (default: all) should use the GPU if available, right?

However, even if available, it seems to do not using it. 
It prints as output: GPU available: True, used: False, and the training script takes 48 hours.

Could you help me with how to make use of GPU?

Thanks in advance

**Comment by laurahanu** [comment]
Hi!

The default for `--device` is actually `None` as seen [here](https://github.com/unitaryai/detoxify/blob/614ed40e5be6a56bdc34d898ad2b9bff103b3c73/train.py#L160) (even though the help text says the default is all - a mistake on our end that we should fix). So it should work if you pass one or multple gpu(s) e.g. `--device 1`.

Hope this helps!

**Comment by grecosalvatore** [comment]
Hi!

Thanks for your very helpful answer. 
If only one GPU is available, the script works with ```--device 0```.
