### ISSUE TITLE
Question regards training with other models

### ISSUE THREAD

**Issue by INFCode** [unitaryai/detoxify#82]
Hello, I am a relatively new user of NLP and I am currently working on a project where I need to use the output of my model as input to your model, which should be applied sequentially.

During the training process, I need to pass the loss through your model without updating any of its weights, and only update the weights of my model. I have a question regarding the training process: Should I follow the steps outlined in the "Training" section of your documentation, or can I use the code provided in the "Prediction" section directly?

I would greatly appreciate your help and guidance on this matter. Thank you in advance.

**Comment by laurahanu** [comment]
Hello,

Sorry for the late reply, in case it's not too late, the examples in the "Prediction" section should work for your use case!
