### ISSUE TITLE
Add license information for toxic-bert on HF

### ISSUE THREAD

**Issue by gabegma** [unitaryai/detoxify#87]
Hi there! 
We would like to use [this model](https://huggingface.co/unitary/toxic-bert) (toxic-bert) on HF, but we couldn't find the license information for it. Is it Apache-2.0, as your repo?
If so, would it be possible to add the license on HF?
Thank you so much!

**Comment by gabegma** [comment]
Hi! Any update on this? Thank you!

**Comment by laurahanu** [comment]
Hello, yes it is the same!

**Comment by gabegma** [comment]
That's awesome, thanks Laura. Would it be possible to add it on HF so it's explicit? 
It should be easy as adding at the top of the [README](https://huggingface.co/unitary/toxic-bert/blob/main/README.md).
```
---
license: apache-2.0
---
```

**Comment by JosephMarinier** [comment]
☝️ That would be really great, it would make my life easier. Would you have a minute to do that @laurahanu? Thank you very much!

**Comment by laurahanu** [comment]
Hi @gabegma @JosephMarinier sorry for the delay, I've now added the license to all the detoxify models on HF!

**Comment by JosephMarinier** [comment]
@laurahanu No worries. That's perfect! Thank you very much for all you do. 🙏

**Comment by gabegma** [comment]
Amazing, thank you so much @laurahanu !!
